# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "2b1f38dc-4f72-45d8-b365-6b904b769cb8"

default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
  increment_build_number

  ENV[“SLACK_URL”] = “https://hooks.slack.com/services/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“

  # build your iOS app
  gym(
    scheme: "FestivalParkApp"
  )

  # upload to HockeyApp
  hockey(
    api_token: "ecd26a68d5a74c658fa456e42a650b96"
  )

slack(
 message: “Beta App successfully released!”
 )
end
