# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FestivalParkApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FestivalParkApp

    pod 'Kingfisher', '~> 3.5'
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'HockeySDK', '~> 4.1.3'
    pod 'SVProgressHUD'
  target 'FestivalParkAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FestivalParkAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
